# Pre-Processing Data
In this section, we will discuss the steps involved in pre-processing data for machine learning models. Pre-processing is a crucial step in the machine learning pipeline as it helps to clean and prepare the data for analysis. The following are some common pre-processing techniques:
1. **Data Cleaning**: This involves handling missing values, removing duplicates, and correcting errors in the dataset. Techniques such as imputation can be used to fill in missing values, while duplicates can be removed to ensure the integrity of the data.
2. **Data Transformation**: This includes scaling, normalization, and encoding categorical variables. Scaling and normalization help to standardize the range of features, while encoding is used to convert categorical variables into a format that can be provided to machine learning algorithms.
3. **Feature Selection**: This process involves selecting the most relevant features for the model. This can be done using techniques such as correlation analysis, mutual information, or using algorithms like Recursive Feature Elimination (RFE).
4. **Data Splitting**: This involves dividing the dataset into training and testing sets. This is important to evaluate the performance of the machine learning model on unseen data. A common split is 80% for training and 20% for testing.


## Machine learning Models need NpArray or DataFrame ?

Machine learning models can work with both NumPy arrays and Pandas DataFrames, but the choice between the two depends on the specific requirements of the model and the data being used.
- **NumPy Arrays**: Many machine learning libraries, such as scikit-learn, primarily use NumPy arrays for their operations. NumPy arrays are efficient for numerical computations and can be easily manipulated for various machine learning tasks. If your data is purely numerical and does not require the additional functionality provided by Pandas, using NumPy arrays can be a good choice.
- **Pandas DataFrames**: Pandas DataFrames are more versatile and provide additional functionality for handling and manipulating data, especially when dealing with mixed data types (numerical and categorical). If your dataset contains categorical variables, missing values, or requires complex data manipulation, using a Pandas DataFrame can be more convenient. Additionally, many machine learning libraries can accept DataFrames directly, making it easier to work with the data without needing to convert it to a NumPy array.

### 1. Imporing Libraries


In [32]:
%pip install numpy
%pip install matplotlib
%pip install pandas
%pip install scikit-learn
#------------------------
import numpy as np
import matplotlib.pyplot as plot
import pandas as pd

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


### 2. Importing Dataset

In [33]:
## Importing Data set using panadas
dataset = pd.read_csv('Data.csv')

### What is Feature and Depended Variable
In machine learning, a **feature** (also known as an independent variable) is an individual measurable property or characteristic of a phenomenon being observed. Features are the input variables that are used to make predictions or classifications in a machine learning model. For example, in a dataset of house prices, features could include the size of the house, the number of bedrooms, and the location.


A **dependent variable** (also known as a target variable) is the outcome or the variable that we are trying to predict or explain. It is dependent on the features. In the house price example, the dependent variable would be the price of the house, which we are trying to predict based on the features.

X = features (independent variables)

y = target variable (dependent variable)

In [ ]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1]

In [35]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [36]:
print(y)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: str


### 3. Missing Values

Why do we need to handle missing values?
- Missing values can lead to biased estimates and reduce the statistical power of the model.
- Many machine learning algorithms cannot handle missing values and will throw an error if they encounter them.
- Handling missing values can improve the performance of the model and lead to better predictions.

## Sykit-learn provides several techniques for handling missing values, such as:
1. **Imputation**: This technique involves filling in the missing values with a specific value, such as the mean, median, or mode of the feature. The `SimpleImputer` class from `sklearn.impute` can be used for this purpose.

In [37]:
### Importing Imputer
from sklearn.impute import SimpleImputer
### Creating Object and specifying what we are going to replace with what Strategy
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
### NOTE: This need to be performed againts the numerical value only
### Column 2 and 3 are numerical so added to fit
### Calculating with FIT
imputer.fit(X[:,1:3])
### Replacing with TRANSFORM
X[:,1:3] = imputer.transform(X[:,1:3])

Using Fit and Transform method of SimpleImputer class, we can handle missing values in our dataset. The `fit` method is used to calculate the imputation values (e.g., mean, median) based on the training data, while the `transform` method is used to apply the imputation to the dataset. Alternatively, we can use the `fit_transform` method to perform both steps in one go. This allows us to effectively handle missing values and prepare our data for machine learning models.

Possible Strategies for Imputation:
- **Mean Imputation**: Replacing missing values with the mean of the feature.
- **Median Imputation**: Replacing missing values with the median of the feature.
- **Mode Imputation**: Replacing missing values with the mode of the feature (most frequent value).

Selecting the appropriate imputation strategy depends on the nature of the data and the distribution of the feature. For example, mean imputation is suitable for normally distributed data, while median imputation is more robust to outliers. Mode imputation is typically used for categorical features.

Selecting Columns with Missing Values:
To identify columns with missing values in a dataset, we can use the `isnull()` function in combination with `sum()` to count the number of missing values in each column. This allows us to focus our imputation efforts on the relevant features and ensure that we are addressing the missing data effectively.
```python
import pandas as pd
# Load the dataset
data = pd.read_csv('dataset.csv')
# Identify columns with missing values
missing_values = data.isnull().sum()
print(missing_values)
```

Selecting Specific columns for Imputation:
To select specific columns for imputation, we can create a list of the column names that we want to impute. We can then use this list to apply the imputation technique only to those columns, while leaving the other columns unchanged. This allows us to target our imputation efforts and ensure that we are only modifying the relevant features in our dataset.

```python
from sklearn.impute import SimpleImputer
# Create a list of columns to impute
columns_to_impute = ['column1', 'column2', 'column3']
# Create an instance of the SimpleImputer
imputer = SimpleImputer(strategy='mean')
# Fit and transform the selected columns
data[columns_to_impute] = imputer.fit_transform(data[columns_to_impute])
```

In [38]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### 4. Data Transformation
Data transformation is a crucial step in the machine learning pipeline that involves modifying the data to make it more suitable for analysis. This can include techniques such as scaling, normalization, and encoding categorical variables. Scaling and normalization help to standardize the range of features, while encoding is used to convert categorical variables into a format that can be provided to machine learning algorithms.

#### 4.1 One-Hot Encoding
One-hot encoding is a technique used to convert categorical variables into a format that can be provided to machine learning algorithms. It creates new binary columns for each category in the original variable, where a value of 1 indicates the presence of that category and a value of 0 indicates its absence. This allows machine learning models to effectively utilize categorical data without assuming any ordinal relationship between the categories.

For Example if we have a categorical variable "Color" with three categories: Red, Green, and Blue, one-hot encoding would create three new binary columns: "Color_Red", "Color_Green", and "Color_Blue". If a data point has the value "Red" for the "Color" variable, the corresponding row in the new columns would be [1, 0, 0], indicating that the color is Red and not Green or Blue.



In [40]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
columTransformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
X = np.array(columTransformer.fit_transform(X))

In [41]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


#### 4.2 Label Encoding
Label encoding is another technique used to convert categorical variables into a format that can be provided to machine learning algorithms. It assigns a unique integer to each category in the original variable. This can be useful for ordinal categorical variables where there is a natural order between the categories. However, it can introduce unintended relationships between categories if used on nominal categorical variables, as the model may interpret the integer values as having a meaningful order.

This can be done using the `LabelEncoder` class from `sklearn.preprocessing`. For example, if we have a categorical variable "Color" with three categories: Red, Green, and Blue, label encoding would assign the values 0, 1, and 2 to these categories respectively. If a data point has the value "Red" for the "Color" variable, it would be encoded as 0, while "Green" would be encoded as 1 and "Blue" as 2.

Best use of this technique is when the categorical variable has an inherent order, such as "Low", "Medium", and "High". In this case, label encoding would assign the values 0, 1, and 2 to these categories respectively, which reflects their natural order. However, for nominal categorical variables like "Color", one-hot encoding is generally preferred to avoid introducing unintended relationships between categories.

In [42]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
y = labelEncoder.fit_transform(y)

In [43]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


#### Do we need to apply Feature Scaling before split or after split?


Feature scaling should be applied after splitting the dataset into training and testing sets. This is because we want to ensure that the scaling is based only on the training data, and not influenced by the testing data. If we apply feature scaling before splitting, we may inadvertently introduce information from the testing set into the training process, which can lead to overfitting and biased performance evaluation. By applying feature scaling after splitting, we can ensure that our model is trained on appropriately scaled data while maintaining the integrity of the testing set for unbiased evaluation.

### 5. Spliting Dataset into Training and Testing Set

Test set neew to be completely unseen to the model during training, so that we can evaluate the performance of the model on new, unseen data. This is typically done by splitting the dataset into a training set and a testing set, where the training set is used to train the model and the testing set is used to evaluate its performance. A common split is 80% for training and 20% for testing, but this can vary depending on the size of the dataset and the specific requirements of the problem at hand.

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size=0.2, random_state=1)

Note: random_state=1 is used to ensure that the split is reproducible, meaning that the same random split will be generated each time the code is run. This allows for consistent results and easier debugging when working with machine learning models.

In [46]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [47]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [48]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [49]:
print(y_test)

[0 1]


### 6. Feature Scaling
Feature scaling is a technique used to standardize the range of features in a dataset. This is important because many machine learning algorithms are sensitive to the scale of the features, and having features on different scales can lead to suboptimal performance. Common feature scaling techniques include normalization (min-max scaling) and standardization (z-score scaling). Normalization scales the features to a range of [0, 1], while standardization centers the features around the mean with a standard deviation of 1. The choice of scaling technique depends on the specific requirements of the machine learning algorithm being used and the distribution of the data.

Type of Scaling:
- **Normalization (Min-Max Scaling)**: This technique scales the features to a range of [0, 1]. It is calculated using the formula: (X - min) / (max - min). Normalization is useful when the data does not follow a Gaussian distribution and when we want to preserve the shape of the original distribution.

<b>Value lies between 0 and 1 after normalization.</b>

- **Standardization (Z-Score Scaling)**: This technique centers the features around the mean with a standard deviation of 1. It is calculated using the formula: (X - mean) / standard_deviation. Standardization is useful when the data follows a Gaussian distribution and when we want to maintain the shape of the original distribution.

<b>Value lies between -3 and 3 after standardization.</b>

What is Gaussian Distribution?
A Gaussian distribution, also known as a normal distribution, is a continuous probability distribution that is symmetric around its mean. It is characterized by its bell-shaped curve, where the mean, median, and mode are all equal. The Gaussian distribution is defined by two parameters: the mean (μ) and the standard deviation (σ). The mean determines the center of the distribution, while the standard deviation controls the spread of the data. Many natural phenomena and measurement errors tend to follow a Gaussian distribution, making it a fundamental concept in statistics and machine learning.

--------------------------

We will apply scalling on both training and testing set, but we will fit the scaler only on the training set to avoid data leakage. This ensures that the scaling is based solely on the training data, and the testing data remains unseen during the fitting process. By doing this, we can evaluate the performance of our machine learning model on new, unseen data without any bias introduced by the scaling process.

<b>Do we apply feature scalling on Dummy Variables?</b>

No, we do not apply feature scaling on dummy variables (one-hot encoded variables) because they are already in a binary format (0 and 1) and do not require scaling. Scaling dummy variables can distort their meaning and lead to incorrect interpretations by the machine learning model. Since dummy variables represent categorical information, they should be left as is to preserve their interpretability and ensure that the model can effectively utilize them for predictions.

# Always Apply Feature Scaling on Numerical Variables and not on Categorical Variables.

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train[:,3:] = ss.fit_transform(X_train[:,3:])
X_test[:,3:] = ss.transform(X_test[:,3:])

What if you want to select column from diffrent indexes for scalling?
To select columns from different indexes for scaling, you can create a list of the column names or indexes that you want to scale. Then, you can apply the scaling technique only to those specific columns while leaving the other columns unchanged. This allows you to target your scaling efforts and ensure that you are only modifying the relevant features in your dataset.
```python
from sklearn.preprocessing import StandardScaler
# Create a list of columns to scale
columns_to_scale = ['column1', 'column2', 'column3']
# Create an instance of the StandardScaler
scaler = StandardScaler()
# Fit and transform the selected columns
data[columns_to_scale] = scaler.fit_transform(data[columns_to_scale])
```
If index 
```python
# Create a list of column indexes to scale
columns_to_scale = [0, 2, 4]  # Example indexes
# Create an instance of the StandardScaler
scaler = StandardScaler()
# Fit and transform the selected columns
data.iloc[:, columns_to_scale] = scaler.fit_transform(data.iloc[:, columns_to_scale])
```

### 7. Conclusion

In conclusion, pre-processing data is a critical step in the machine learning pipeline that involves various techniques to clean and prepare the data for analysis. Handling missing values through imputation, transforming data using encoding techniques, selecting relevant features, and splitting the dataset into training and testing sets are essential steps to ensure the quality and effectiveness of machine learning models. Additionally, applying feature scaling to numerical variables while leaving categorical variables unchanged can help improve model performance. By following these pre-processing steps, we can enhance the accuracy and reliability of our machine learning models when making predictions on new, unseen data.